
message0 = "Argument 1 is not a valid monophonic array, expecting array shape (n,) got %s "
message1 = "Argument 1 is not a valid monophonic array, expecting numpy.ndarray type got %s "
message2 = 'Argument 1 cannot be an empty buffer.'
message3 = 'RMS threshold %s value cannot be > average RMS value %s.'
message4 = "Argument 1 is not a valid stereophonic array, expecting array shape (n, 2) got %s "
message5 = "Argument 1 is not a valid stereophonic array, expecting numpy.ndarray type got %s "
message6 = "The mixer has not been initialized."
message7 = "This current version is not compatible with channel number > 2 "
message8 = "Argument 1 must be a float value in range ]0.0 ... 1.0]"
message9 = "Argument 1 must be a float value in range [0.0 ... 1.0]"
message20 = "Argument %s must be a float in the interval [0.0 ... 1.0]"
message10 = "Argument 2 value is not a valid sample rate got %s \nValid sample rate %s"
message15 = "Invalid sample rate value got %s \nValid sample rate %s"
message11 = "Argument 1 is not a valid monophonic array"
message12 = 'Data sample length cannot be zero.'
message13 = 'Argument 2 cannot be null'
message14 = "Argument 1 is not a valid stereophonic array"
message16 = "Signal length cannot be null or < 0"
message17 = "Signal frequency cannot be < 0"
message18 = "Constant c (signal offset component) must be in range [-1.0 ... 1.0]"
message19 = "Constant phi (radians) must be in range [-π ... +π]"
message21 = "Argument %s cannot be None or NoneType"
message22 = "Argument %s is not a valid monophonic array"
message23 = "Argument %s is not a pygame.mixer.sound object type"
message24 = "Argument %s cannot be < 0"
message25 = "%s value must be < %s, got %s "
message26 = "Argument %s is not a valid stereophonic array"
message27 = "Invalid datatype %s for sound data samples"
message28 = "Invalid monophonic array shapes"
message29 = "Invalid stereophonic array shapes"
message30 = "Invalid monophonic or stereophonic array"
message31 = "Invalid array type, expecting numpy.ndarray got %s "
message32 = "Invalid file format, expecting a wav format got %s"
message33 = "File extension is not recognize."
message34 = "Invalid type for argument %s, expecting %s got %s"
message35 = "Argument %s must be >=%s got %s"
message36 = "An error occurred during the recording\n Error : %s"
message37 = "An error has occurred when saving a sound file to disk.\n Error : %s"
message38 = "Cannot close the file.\n Error : %s"
message39 = "Argument %s cannot be converted into a Pygame sound array."
message40 = "Argument %s (n_) is not a power of 2, got %s"
message41 = "Argument %s cannot be < 1"
message42 = "Argument %s cannot be <= 0"
message43 = "Argument %s cannot be > %s"
message44 = "Argument must be in range %s <= %s < %s, got %s"
message45 = "Argument must be in range %s <= %s <= %s, got %s"
message46 = "Argument must be in range %s < %s < %s, got %s"
message47 = "Argument must be in range %s < %s <= %s, got %s"
